baseURL = "https://www.codedbearder.com/"
languageCode = "en-us"
title = "codedbearder"
copyright = "&copy; Arnar Gauti Ingason"
theme = "hugo_theme_pickles"

[params]
  custom_css = ["/css/custom.css"]
  paginate = 5
  github = "arnarg"
  linkedin = "arnari"
  # Disable Disqus
  disqus = false
  # Disable Google analytics
  ga_api_key = false
  favicon = "/images/favicon.png"
  # Me
  author = "Arnar Gauti Ingason"
  contact = "mailto:codedbearder@arnarg.fastmail.com"
  avatar = "/images/avatar.jpg"
